# Generated by Django 6.0.2 on 2026-02-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAPP', '0002_userprofile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(choices=[('recommendation', 'Recommendation'), ('alert', 'Alert'), ('reclamation', 'Reclamation')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
